### ISSUE TITLE
integrated_nodes.yaml: Ignoring integrated node standard2, failed processing workflow

### ISSUE THREAD

**Issue by MokkaBoss1** [palant/integrated-nodes-comfyui#8]
Hi,

after having created a number of integrated nodes Yesterday, I noticed when restarting comfy this morning that there were lots of errors in the log and my new nodes were showing as red in my workflow.

I am enclosing below the messages related to one of the nodes but this replicated for al my integrated nodes

Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 546, in create_integrated_node
    (processors, inputs, outputs, is_output_node) = process_workflow(workflow, export_outputs, rename_outputs)
  File "F:\ComfyUI\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 401, in process_workflow
    nodes, exported_inputs = create_nodes(workflow)
  File "F:\ComfyUI\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 364, in create_nodes
    node.assign_defaults_map(node_workflow.get("inputs", {}))
  File "F:\ComfyUI\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 104, in assign_defaults_map
    self.input_by_name(name).set_default_value(value)
  File "F:\ComfyUI\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 69, in input_by_name
    return next(input for input in self.inputs if input.name == name)
StopIteration
integrated_nodes.yaml: Ignoring integrated node standard2, failed processing workflow

any ideas?

thanks

Mokkaboss1

**Comment by palant** [comment]
Could you attach the file `F:\ComfyUI\ComfyUI\custom_nodes\integrated-nodes-comfyui\standard2.json`? According to the error, this workflow contains values for inputs that are missing from the actual nodes. Unless these nodes changed after the workflow was saved, that’s unexpected.

Use of primitives shouldn’t matter, ComfyUI simply assigns the value of primitives to their respective input when saving.

**Comment by palant** [comment]
I went through your workflow. Could it be that you have both https://github.com/twri/sdxl_prompt_styler and https://github.com/sipherxyz/comfyui-art-venture installed? They both define `SDXLPromptStyler` node but the latter has an older version of it where `style_positive` and `style_negative` inputs are missing. I suspect that this is the issue here – the integrated node initializes when the node from `comfyui-art-venture` already exists and before it has been overwritten by the node from `sdxl_prompt_styler` which you are actually using.

If that’s the case, making sure that integrated nodes always load last should solve this issue. See [these instructions](https://github.com/palant/integrated-nodes-comfyui#using-custom-nodes-in-integrated-nodes).

**Comment by palant** [comment]
Could you comment whether this solved your issue?

**Comment by MokkaBoss1** [comment]
Hi apologies for my delay. Will send some feedback today

Regards

Mokkaboss1

**Comment by MokkaBoss1** [comment]
Hi, managed to test and yes it is working.

1 small tweak I had to make was in the YAML file

custom_nodes_last:
    custom_nodes: F:\ComfyUI\ComfyUI\custom_nodes\custom_nodes_last


I had put the whole path in not just 1:1 as in the instructions.

Many thanks

Mokkaboss1
